apiVersion: v1
kind: Secret
metadata:
  name: amnezia-bot-secrets
  namespace: amnezia
type: Opaque
stringData:
  BOT_TOKEN: "123456:ABC-DEF..."
  DATABASE_URL: "postgres://amnezia:pass@postgres.amnezia.svc:5432/amnezia_bot?sslmode=disable"
  # содержимое приватного SSH-ключа; монтируется файлом id_ed25519
  ssh_private_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
